# To merge egm pull request at 11:58 am 

name: Merge EGM Branch
on:
  pull_request:
    branches:
      - egm
  schedule:
    - cron: 58 11 * * *

jobs: 
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1.x
        env:
          GITHUB_TOKEN: $
